language: node_js
node_js:
    - "5"

deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: itsacoyoteworkshop.com
    endpoint: itsacoyoteworkshop.com.s3-website-us-east-1.amazonaws.com
    region: us-east-1
    acl: public_read
    local_dir: public